# Maximum width of each line
max_width = 100

# Number of spaces per tab
tab_spaces = 4

# Use spaces instead of tabs
hard_tabs = false

# Merge imports into a single line if possible
imports_granularity = "Crate"

# Format comments
comment_width = 80

# Format strings
format_strings = true

# Format macro invocations
format_macro_matchers = true

# Format macro bodies
format_macro_bodies = true

# Reorder imports
reorder_imports = true

# Group imports
group_imports = "StdExternalCrate"

# Reorder modules
reorder_modules = true

# Group imports
imports_layout = "HorizontalVertical"

# Merge multiple derives into a single line
merge_derives = true

# Format code inside macro declarations
format_code_in_doc_comments = true

# Remove nested parens
remove_nested_parens = true

# Struct field alignment
struct_field_align_threshold = 20

# Enum variant alignment
enum_discrim_align_threshold = 20

# Chain width for breaking
chain_width = 60

# Array element width
array_width = 60

# Where clause formatting
where_single_line = true

# Trailing comma behavior
trailing_comma = "Vertical"

# Control brace style
control_brace_style = "AlwaysSameLine"

# Empty line settings
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
