name: Cron Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build generator
        run: cargo build --package tele-api-spec --bin tele-api-spec
      - name: Generate schemas
        run: cargo run --package tele-api-spec --bin tele-api-spec -- production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
